"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SignalType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SignalTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SignalType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WV_2G: _SignalType.ValueType  # 0
    WV_4G: _SignalType.ValueType  # 1
    WV_868: _SignalType.ValueType  # 2
    CT_2G: _SignalType.ValueType  # 3
    CT_4G: _SignalType.ValueType  # 4
    NB_IOT: _SignalType.ValueType  # 5
    CAT_LTE: _SignalType.ValueType  # 6

class SignalType(_SignalType, metaclass=_SignalTypeEnumTypeWrapper): ...

WV_2G: SignalType.ValueType  # 0
WV_4G: SignalType.ValueType  # 1
WV_868: SignalType.ValueType  # 2
CT_2G: SignalType.ValueType  # 3
CT_4G: SignalType.ValueType  # 4
NB_IOT: SignalType.ValueType  # 5
CAT_LTE: SignalType.ValueType  # 6
Global___SignalType: _TypeAlias = SignalType  # noqa: Y015

@_typing.final
class LastValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    SIGNAL_TYPE_FIELD_NUMBER: _builtins.int
    ts: _builtins.int
    value: _builtins.float
    channel_id: _builtins.int
    signal_type: Global___SignalType.ValueType
    def __init__(
        self,
        *,
        ts: _builtins.int = ...,
        value: _builtins.float = ...,
        channel_id: _builtins.int = ...,
        signal_type: Global___SignalType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "key", b"key", "signal_type", b"signal_type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "key", b"key", "signal_type", b"signal_type", "ts", b"ts", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_key: _TypeAlias = _typing.Literal["channel_id", "signal_type"]  # noqa: Y015
    _WhichOneofArgType_key: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_key) -> _WhichOneofReturnType_key | None: ...

Global___LastValue: _TypeAlias = LastValue  # noqa: Y015

@_typing.final
class Sample(_message.Message):
    """One sample to insert by channel_id - normally 4 samples per transmission"""

    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    TS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    channel_id: _builtins.int
    ts: _builtins.int
    """epoch seconds"""
    value: _builtins.float
    def __init__(
        self,
        *,
        channel_id: _builtins.int = ...,
        ts: _builtins.int = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "ts", b"ts", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Sample: _TypeAlias = Sample  # noqa: Y015

@_typing.final
class LoggerSignal(_message.Message):
    """Typically one status per transmission (but occurs at every sample)"""

    DESCRIPTOR: _descriptor.Descriptor

    TS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    ts: _builtins.int
    value: _builtins.float
    """e.g. -80"""
    def __init__(
        self,
        *,
        ts: _builtins.int = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ts", b"ts", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoggerSignal: _TypeAlias = LoggerSignal  # noqa: Y015

@_typing.final
class LoggerBatch(_message.Message):
    """One logger batch with multiple samples (one or more transmissions)"""

    DESCRIPTOR: _descriptor.Descriptor

    LOGGER_ID_FIELD_NUMBER: _builtins.int
    BATTERY_FIELD_NUMBER: _builtins.int
    LAST_SEEN_FIELD_NUMBER: _builtins.int
    SIGNAL_TYPE_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    SIGNALS_FIELD_NUMBER: _builtins.int
    LAST_VALUES_FIELD_NUMBER: _builtins.int
    logger_id: _builtins.int
    battery: _builtins.float
    """mean value of V in transmission"""
    last_seen: _builtins.int
    """typically the newest ts in samples (or packet time)"""
    signal_type: Global___SignalType.ValueType
    @_builtins.property
    def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___Sample]: ...
    @_builtins.property
    def signals(self) -> _containers.RepeatedCompositeFieldContainer[Global___LoggerSignal]: ...
    @_builtins.property
    def last_values(self) -> _containers.RepeatedCompositeFieldContainer[Global___LastValue]: ...
    def __init__(
        self,
        *,
        logger_id: _builtins.int = ...,
        battery: _builtins.float = ...,
        last_seen: _builtins.int = ...,
        signal_type: Global___SignalType.ValueType = ...,
        samples: _abc.Iterable[Global___Sample] | None = ...,
        signals: _abc.Iterable[Global___LoggerSignal] | None = ...,
        last_values: _abc.Iterable[Global___LastValue] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["battery", b"battery", "last_seen", b"last_seen", "last_values", b"last_values", "logger_id", b"logger_id", "samples", b"samples", "signal_type", b"signal_type", "signals", b"signals"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoggerBatch: _TypeAlias = LoggerBatch  # noqa: Y015

@_typing.final
class Gateway(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GATEWAY_ID_FIELD_NUMBER: _builtins.int
    LAST_SEEN_FIELD_NUMBER: _builtins.int
    LAST_SIGNAL_FIELD_NUMBER: _builtins.int
    SIGNAL_TYPE_FIELD_NUMBER: _builtins.int
    gateway_id: _builtins.int
    last_seen: _builtins.int
    last_signal: _builtins.float
    signal_type: Global___SignalType.ValueType
    def __init__(
        self,
        *,
        gateway_id: _builtins.int = ...,
        last_seen: _builtins.int = ...,
        last_signal: _builtins.float = ...,
        signal_type: Global___SignalType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway_id", b"gateway_id", "last_seen", b"last_seen", "last_signal", b"last_signal", "signal_type", b"signal_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Gateway: _TypeAlias = Gateway  # noqa: Y015

@_typing.final
class Batch(_message.Message):
    """Batch of multiple loggers"""

    DESCRIPTOR: _descriptor.Descriptor

    TRANSMISSION_ID_FIELD_NUMBER: _builtins.int
    LOGGER_BATCH_FIELD_NUMBER: _builtins.int
    transmission_id: _builtins.str
    """uuid"""
    @_builtins.property
    def logger_batch(self) -> _containers.RepeatedCompositeFieldContainer[Global___LoggerBatch]: ...
    def __init__(
        self,
        *,
        transmission_id: _builtins.str = ...,
        logger_batch: _abc.Iterable[Global___LoggerBatch] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["logger_batch", b"logger_batch", "transmission_id", b"transmission_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Batch: _TypeAlias = Batch  # noqa: Y015
