# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intabcloud_telemetry_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dintabcloud_telemetry_v1.proto\x12\x17intabcloud.telemetry.v1\"\x7f\n\tLastValue\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x14\n\nchannel_id\x18\x03 \x01(\x05H\x00\x12:\n\x0bsignal_type\x18\x04 \x01(\x0e\x32#.intabcloud.telemetry.v1.SignalTypeH\x00\x42\x05\n\x03key\"7\n\x06Sample\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x02\")\n\x0cLoggerSignal\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x02\"\xa1\x02\n\x0bLoggerBatch\x12\x11\n\tlogger_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\x02\x12\x11\n\tlast_seen\x18\x03 \x01(\x03\x12\x38\n\x0bsignal_type\x18\x04 \x01(\x0e\x32#.intabcloud.telemetry.v1.SignalType\x12\x30\n\x07samples\x18\x05 \x03(\x0b\x32\x1f.intabcloud.telemetry.v1.Sample\x12\x36\n\x07signals\x18\x06 \x03(\x0b\x32%.intabcloud.telemetry.v1.LoggerSignal\x12\x37\n\x0blast_values\x18\x07 \x03(\x0b\x32\".intabcloud.telemetry.v1.LastValue\"\x7f\n\x07Gateway\x12\x12\n\ngateway_id\x18\x01 \x01(\x05\x12\x11\n\tlast_seen\x18\x02 \x01(\x03\x12\x13\n\x0blast_signal\x18\x03 \x01(\x02\x12\x38\n\x0bsignal_type\x18\x04 \x01(\x0e\x32#.intabcloud.telemetry.v1.SignalType\"\\\n\x05\x42\x61tch\x12\x17\n\x0ftransmission_id\x18\x01 \x01(\t\x12:\n\x0clogger_batch\x18\x02 \x03(\x0b\x32$.intabcloud.telemetry.v1.LoggerBatch*]\n\nSignalType\x12\t\n\x05WV_2G\x10\x00\x12\t\n\x05WV_4G\x10\x01\x12\n\n\x06WV_868\x10\x02\x12\t\n\x05\x43T_2G\x10\x03\x12\t\n\x05\x43T_4G\x10\x04\x12\n\n\x06NB_IOT\x10\x05\x12\x0b\n\x07\x43\x41T_LTE\x10\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intabcloud_telemetry_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNALTYPE._serialized_start=802
  _SIGNALTYPE._serialized_end=895
  _LASTVALUE._serialized_start=58
  _LASTVALUE._serialized_end=185
  _SAMPLE._serialized_start=187
  _SAMPLE._serialized_end=242
  _LOGGERSIGNAL._serialized_start=244
  _LOGGERSIGNAL._serialized_end=285
  _LOGGERBATCH._serialized_start=288
  _LOGGERBATCH._serialized_end=577
  _GATEWAY._serialized_start=579
  _GATEWAY._serialized_end=706
  _BATCH._serialized_start=708
  _BATCH._serialized_end=800
# @@protoc_insertion_point(module_scope)
