# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libs/intabcloud_telemetry_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"libs/intabcloud_telemetry_v1.proto\x12\x17intabcloud.telemetry.v1\"7\n\x06Sample\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x02\";\n\x0cLoggerStatus\x12\n\n\x02ts\x18\x01 \x01(\x03\x12\x0e\n\x06signal\x18\x02 \x01(\x02\x12\x0f\n\x07\x62\x61ttery\x18\x03 \x01(\x02\"\x9c\x01\n\x0bLoggerBatch\x12\x11\n\tlogger_id\x18\x01 \x01(\x05\x12\x11\n\tlast_seen\x18\x02 \x01(\x03\x12\x30\n\x07samples\x18\x03 \x03(\x0b\x32\x1f.intabcloud.telemetry.v1.Sample\x12\x35\n\x06status\x18\x04 \x03(\x0b\x32%.intabcloud.telemetry.v1.LoggerStatus\"C\n\x05\x42\x61tch\x12:\n\x0clogger_batch\x18\x01 \x03(\x0b\x32$.intabcloud.telemetry.v1.LoggerBatchb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libs.intabcloud_telemetry_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLE._serialized_start=63
  _SAMPLE._serialized_end=118
  _LOGGERSTATUS._serialized_start=120
  _LOGGERSTATUS._serialized_end=179
  _LOGGERBATCH._serialized_start=182
  _LOGGERBATCH._serialized_end=338
  _BATCH._serialized_start=340
  _BATCH._serialized_end=407
# @@protoc_insertion_point(module_scope)
