"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Sample(_message.Message):
    """One sample to insert by channel_id - normally 4 samples per transmission"""

    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    TS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    channel_id: _builtins.int
    ts: _builtins.int
    """epoch seconds"""
    value: _builtins.float
    def __init__(
        self,
        *,
        channel_id: _builtins.int = ...,
        ts: _builtins.int = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "ts", b"ts", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Sample: _TypeAlias = Sample  # noqa: Y015

@_typing.final
class LoggerStatus(_message.Message):
    """Typically one status per transmission (but occurs at every sample)"""

    DESCRIPTOR: _descriptor.Descriptor

    TS_FIELD_NUMBER: _builtins.int
    SIGNAL_FIELD_NUMBER: _builtins.int
    BATTERY_FIELD_NUMBER: _builtins.int
    ts: _builtins.int
    signal: _builtins.float
    """e.g. -80"""
    battery: _builtins.float
    """e.g. 3.652"""
    def __init__(
        self,
        *,
        ts: _builtins.int = ...,
        signal: _builtins.float = ...,
        battery: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["battery", b"battery", "signal", b"signal", "ts", b"ts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoggerStatus: _TypeAlias = LoggerStatus  # noqa: Y015

@_typing.final
class LoggerBatch(_message.Message):
    """One logger batch with multiple samples (one or more transmissions)"""

    DESCRIPTOR: _descriptor.Descriptor

    LOGGER_ID_FIELD_NUMBER: _builtins.int
    LAST_SEEN_FIELD_NUMBER: _builtins.int
    SAMPLES_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    logger_id: _builtins.int
    last_seen: _builtins.int
    """typically the newest ts in samples (or packet time)"""
    @_builtins.property
    def samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___Sample]: ...
    @_builtins.property
    def status(self) -> _containers.RepeatedCompositeFieldContainer[Global___LoggerStatus]: ...
    def __init__(
        self,
        *,
        logger_id: _builtins.int = ...,
        last_seen: _builtins.int = ...,
        samples: _abc.Iterable[Global___Sample] | None = ...,
        status: _abc.Iterable[Global___LoggerStatus] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["last_seen", b"last_seen", "logger_id", b"logger_id", "samples", b"samples", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoggerBatch: _TypeAlias = LoggerBatch  # noqa: Y015

@_typing.final
class Batch(_message.Message):
    """Batch of multiple loggers"""

    DESCRIPTOR: _descriptor.Descriptor

    LOGGER_BATCH_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def logger_batch(self) -> _containers.RepeatedCompositeFieldContainer[Global___LoggerBatch]: ...
    def __init__(
        self,
        *,
        logger_batch: _abc.Iterable[Global___LoggerBatch] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["logger_batch", b"logger_batch"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Batch: _TypeAlias = Batch  # noqa: Y015
